### ISSUE TITLE
Audio volume resets

### ISSUE THREAD

**Issue by Konkonfaux** [fgsfdsfgs/doukutsupsx#1]
I was playing the newest release, and noticed audio volume will reset to default seemingly every new screen.

**Comment by fgsfdsfgs** [comment]
Are you sure you didn't load a save after modifying it? Volume settings are saved in the save, so if you change it and then load, it'll reload the old ones.

**Comment by fgsfdsfgs** [comment]
Should be fixed in b1cd9eb. Give this a test and see if it works correctly now.
[doukutsu.zip](https://github.com/fgsfdsfgs/doukutsupsx/files/7541464/doukutsu.zip)

**Comment by Konkonfaux** [comment]
The issue is solved on my end.
