### ISSUE TITLE
Crashed with error when talking to Jack

### ISSUE THREAD

**Issue by ualaa1** [fgsfdsfgs/doukutsupsx#5]
Using Duckstation playing Test 5. Shows an error number with red screen.
Savestate: [DOUKUTSUEXE_1.zip](https://github.com/fgsfdsfgs/doukutsupsx/files/8694402/DOUKUTSUEXE_1.zip)
Screenshot:
![DOUKUTSUEXE_2022-05-14_23-07-42](https://user-images.githubusercontent.com/68984176/168459589-c2b77449-909a-432d-b265-f74943b9bb8d.png)

**Comment by fgsfdsfgs** [comment]
That's interesting, it looks like you had the inventory script loaded when you talked to him for some reason. Did you do anything out of the ordinary before talking to him, like using items in the inventory screen?

**Comment by ualaa1** [comment]
I think I may have used the map prior

**Comment by ualaa1** [comment]
Here's a memory card save: [doukutsu_test5_2_1.zip](https://github.com/fgsfdsfgs/doukutsupsx/files/8725104/doukutsu_test5_2_1.zip)
Before talking to Jack, I was able to trigger the bug by going into the menu and looking at the map. I did it next to Jack and I went into the map by using the menu and not the map button.

**Comment by fgsfdsfgs** [comment]
I see the issue. The script is not swapped back to the map script if you activate the map from within the inventory screen.

**Comment by fgsfdsfgs** [comment]
Fixed in 8516ab1. Will be in the next build.
