### ISSUE TITLE
do you accept this rom to be in cavestory.org 

### ISSUE THREAD

**Issue by dananothername** [fgsfdsfgs/doukutsupsx#8]
hi fgsfdsfgs is this your nick name 
or can you past a better one 
anyway it will be cool if this rom on the site

**Comment by fgsfdsfgs** [comment]
You can put this up on cavestory.org if you want. You can use `fgsfds` for the nickname.

**Comment by dananothername** [comment]
one more question is this for ps1 or 2

**Comment by fgsfdsfgs** [comment]
This is for the PS1.

**Comment by dananothername** [comment]
i just TASed it to see how it runs frame by frame 
https://m.youtube.com/watch?v=zrQ8G3Ig9so
bugs that i found in test 6:
-quote can't do multi-tasks i had to release the jump key to fire like it acept only 3 input per frame unlike the freeware where you can jump,fire,change wepon ,open menu,hold right up and down all in one frame 
-it takes a lot of time to change the rooms 
- those two i am not sure about :there is frame skipping so add option for enabling 60fps +the player act late 4 frames means if you press down you got to hold it and wait 4 frames for quote to look down

**Comment by fgsfdsfgs** [comment]
There shouldn't be anything preventing more than 3 inputs to be accepted per frame.
The game times its frames based on a 100Hz root counter. Every 2 ticks it reads inputs, processes a frame and renders it. In 60Hz NTSC it will not match the vblank rate, so it might cause some weird shit to happen.
